baseURL = 'https://devrig.dev/'
languageCode = 'en-us'
title = 'devrig - AI-Empowered Development Environment'
theme = 'devrig-minimal'

[params]
  description = 'The command to start the AI-empowered development environment of your project'
  github = 'https://github.com/jonnyzzz/devrig.dev'

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ['HTML']

[[menus.main]]
  name = 'Home'
  url = '/'
  weight = 1

[[menus.main]]
  name = 'Features'
  url = '/features/'
  weight = 2

[[menus.main]]
  name = 'Download'
  url = '/download/'
  weight = 3

[[menus.main]]
  name = 'Contribute'
  url = 'https://github.com/jonnyzzz/devrig.dev'
  weight = 4
  [menus.main.params]
    icon = 'github'
